const {
  sequelize,
  Sequelize,
  notNullStringType,
  allowNullStringType,
  textType,
  decimalType,
  tinyIntType,
  charType,
  nowTimestampType,
  emptyIntegerType,
} = require('./db');

const Product = sequelize.define('products', {
  sku: {
    type: Sequelize.STRING,
    allowNull: false,
    primaryKey: true,
  },
  description: textType,
  title: notNullStringType,
  template_page: allowNullStringType,
  comment: textType,
  comment_right: textType,
  thumb: allowNullStringType,
  image: allowNullStringType,
  price: decimalType,
  advanced_pricing: tinyIntType,
  wholesale: allowNullStringType,
  tax_category: allowNullStringType,
  nontaxable: charType,
  weight: notNullStringType,
  size: allowNullStringType,
  color: allowNullStringType,
  option_type: allowNullStringType,
  options_advanced: tinyIntType,
  gift_cert: allowNullStringType,
  related: textType,
  featured: allowNullStringType,
  download: allowNullStringType,
  dl_type: allowNullStringType,
  dl_location: allowNullStringType,
  inactive: tinyIntType,
  url: allowNullStringType,
  sale_price: allowNullStringType,
  image_large: allowNullStringType,
  prod_discount: decimalType,
  prod_teaser: allowNullStringType,
  display_site: notNullStringType,
  meta_key_words: allowNullStringType,
  meta_page_title: allowNullStringType,
  meta_desc: allowNullStringType,
  extended: textType,
  product_type: {
    type: Sequelize.STRING,
    allowNull: false,
    defaultValue: 'Physical',
  },
  url_override: allowNullStringType,
  slug: allowNullStringType,
  last_modified: nowTimestampType,
  priority: allowNullStringType,
  access_control: tinyIntType,
  supplier: emptyIntegerType,
});

module.exports = Product;
